version: '3'

services:
  web:
    build: .
    command: bash -c "python manage.py makemigrations FezComicServerPython && python manage.py migrate && python manage.py loaddata init.json && python manage.py runserver 0.0.0.0:8000"
    container_name: FezComicRESTPy-Service
    volumes:
       - .:/FezComicRESTPy-Service
    ports:
       - "8000:8000"
