version: '3'

services:
  db:
    image: mysql:5.7
    command: --max-allowed-packet=256M
    restart: always
    environment:
      MYSQL_DATABASE: 'iweb'
      MYSQL_USER: 'iweb'
      MYSQL_PASSWORD: 'iweb'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  web:
    build: .
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    container_name: FezComicRESTPy-Service
    volumes:
       - .:/FezComicRESTPy-Service
    ports:
       - "8000:8000"
