# Generated by Django 2.1.5 on 2019-01-29 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=45)),
                ('mensaje', models.CharField(blank=True, max_length=400, null=True)),
            ],
            options={
                'db_table': 'comentario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, unique=True)),
                ('isbn', models.CharField(blank=True, max_length=13, null=True)),
                ('foto', models.TextField(blank=True, null=True)),
                ('anotacion_privada', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'comic',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'like',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'rol',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, unique=True)),
                ('anotacion_privada', models.CharField(blank=True, max_length=200, null=True)),
                ('genero', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'serie',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ComicHasSerie',
            fields=[
                ('id_comic', models.ForeignKey(db_column='id_comic', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='FezComicServerPython.Comic')),
                ('anotacion_publica', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'comic_has_serie',
                'managed': False,
            },
        ),
    ]
