# Generated by Django 2.1.5 on 2019-01-29 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FezComicServerPython', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='like',
            options={'managed': True},
        ),
    ]
