# Generated by Django 2.1.5 on 2019-01-31 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FezComicServerPython', '0002_auto_20190129_1837'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='comichasserie',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='like',
            options={'managed': False},
        ),
    ]
