# Generated by Django 2.1.5 on 2019-01-31 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FezComicServerPython', '0003_auto_20190131_0140'),
    ]

    operations = [
        migrations.AddField(
            model_name='comichasserie',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comichasserie',
            name='id_serie',
            field=models.ForeignKey(db_column='id_serie', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='FezComicServerPython.Serie'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comichasserie',
            name='id_comic',
            field=models.ForeignKey(db_column='id_comic', on_delete=django.db.models.deletion.DO_NOTHING, to='FezComicServerPython.Comic'),
        ),
        migrations.AlterUniqueTogether(
            name='comichasserie',
            unique_together={('id_comic', 'id_serie')},
        ),
    ]
