# Generated by Django 2.1.5 on 2019-01-31 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FezComicServerPython', '0004_auto_20190131_0142'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comichasserie',
            unique_together={('id', 'id_comic', 'id_serie')},
        ),
    ]
