# Generated by Django 2.1.5 on 2019-01-31 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FezComicServerPython', '0005_auto_20190131_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comichasserie',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
