# Generated by Django 2.1.5 on 2019-02-02 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FezComicServerPython', '0006_auto_20190131_0145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comichasserie',
            options={'managed': False},
        ),
    ]
